version: '3.8'
services:
  drupal:
    image: drupal:10
    container_name: drupal_local
    ports:
      - "8080:80"
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_USER=drupal
      - DRUPAL_DATABASE_PASSWORD=drupal
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_PORT=3306

  db:
    image: mysql:5.7
    container_name: drupal_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  drupal_data:
  db_data: